import React from "react";

const areas = [
    'Limassol - Agia Fyla',
    'Strovolos',
    'Limassol - Mesa Geitonia',
    'Lakatameia',
    'Limassol',
    'Erimi',
    'Germasogeia',
    'Aradippou',
    'Larnaca - Finikoudes',
    'Limassol - Petrou Kai Pavlou',
    'Kallepeia',
    'Aglantzia',
    'Limassol - Agios Nicolaos',
    'Strovolos - Acropolis',
    'Kato Polemidia',
    'Latsia',
    'Nicosia - Agios Dometios',
    'Nicosia - Agios Andreas',
    'Limassol - Neapolis',
    'Egkomi - Makedonitissa',
    'Limassol - Linopetra',
    'Germasogeia Tourist Area',
    'Konia',
    'Nicosia - Lykabittos',
    'Lythrodontas',
    'Limassol - Agia Zoni',
    'Psimolofou',
    'Pyrgos Lemesou',
    'Limassol - Katholiki',
    'Kiti',
    'Dekeleia',
    'Agios Athanasios',
    'Agios Tychon Tourist Area',
    'Nicosia - Town Center',
    'Oroklini',
    'Nicosia - Palouriotissa',
    'Agioi Omologites',
    'Tsada',
    'Larnaca - Harbor',
    'Mesa Geitonia',
    'Mouttagiaka Tourist Area',
    'Kalithea',
    'Perivolia Larnakas',
    'Strovolos - Archangelos',
    'Larnaca - Town Center',
    'Limassol - Zakaki',
    'Pegeia',
    'Kouklia Pafou',
    'Tala',
    'Paphos - Kato Paphos',
    'Limnatis',
    'Agios Tychon',
    'Chlorakas',
    'Pissouri',
    'Paphos - Town Center',
    'Paphos - Tombs Of the Kings',
    'Geroskipou',
    'Limassol - Agios Ioannis',
    'Larnaca - Kamares',
    'Limassol - Historical Center',
    'Souni',
    'Trachoni Lemesou',
    'Paramali',
    'Nicosia - Kaimakli',
    'Pyla',
    'Geri',
    'Anogyra',
    'Limassol - Apostolos Andreas',
    'Parekklisia Tourist Area',
    'Protaras',
    'Egkomi',
    'Livadia Larnakas',
    'Ypsonas',
    'Strovolos - Dasoupolis',
    'Pyrga Larnakas',
    'Dali',
    'Kissonerga',
    'Pera',
    'Limassol - Ekali',
    'Paramytha',
    'Mouttagiaka',
    'Pyrgos Lemesou Tourist Area',
    'Paphos - Anavargos',
    'Limassol - Omonia',
    'Pera Chorio',
    'Monagri',
    'Tseri',
    'Empa',
    'Limassol - Limassol Marina',
    'Oroklini Tourist Area',
    'Asomatos Lemesou',
    'Mazotos',
    'Larnaca - Makenzy',
    'Parekklisia',
    'Panthea',
    'Limassol - Kapsalos',
    'Agrokipia',
    'Agioi Trimithias',
    'Alassa',
    'Limassol - Agios Nektarios',
    'Kalo Chorio Lemesou',
    'Lakatameia - Anthoupolis',
    'Apesia',
    'Tersefanou',
    'Alampra',
    'Kolossi',
    'Agios Mamas',
    'Egkomi - Parissinos',
    'Dromolaxia',
    'Larnaca - Agioi Anargyroi',
    'Psematismenos',
    'Palaiometocho',
    'Nea Ledras',
    'Stelmek Area',
    'Pentakomo',
    'Meneou',
    'Agios Amvrosios Lemesou',
    'Pachna',
    'Pera Pedi',
    'Moni',
    'Monagroulli',
    'Moniatis',
    'Limassol - Anthoupoli',
    'Peristerona Pafou',
    'Marathounta',
    'Deryneia',
    'Zoopigi',
    'Geroskipou Tourist Area',
    'Avgorou',
    'Anglisides',
    'GSP Area',
    'Limassol - Tsiflikoudia',
    'Pano Polemidia',
    'Vasa Koilaniou',
    'Koloni',
    'Kapparis',
    'Platres Pano',
    'Ayia Napa',
    'Polemi',
    'Agios Therapon',
    'Aphrodite hills',
    'Geroskipou - Neapolis',
    'Fyti',
    'Paphos - Universal',
    'Limassol - Tsirion',
    'Lofou',
    'Psevdas',
    'Ineia',
    'Tremithousa',
    'Tserkez Tsiftlik (Tserkezoi)',
    'Lasa',
    'Kotsiatis',
    'Agros',
    'Mandria Lemesou',
    'Lefkara Pano',
    'Agios Epifanios Oreinis',
    'Fasouri',
    'Palodeia',
    'Mathiatis',
    'Limassol - Agios Georgios',
    'Agia Triada',
    'Vouni',
    'Alethriko',
    'Nisou',
    'Kampia',
    'Sia',
    'Anglikos Stratos Dekeleias',
    'Eptagoneia',
    'Episkopi Lemesou',
    'Paphos - Vasiliko',
    'Drouseia',
    'Anarita',
    'Treis Elies',
    'Foini',
    'Zygi',
    'Trimiklini',
    'Deftera Pano',
    'Laneia',
    'Skoulli',
    'Archimandrita Kato',
    'Cape Greko',
    'Paralimni',
    'Arakapas',
    'Saittas',
    'Athienou',
    'Doros',
    'Kaminaria',
    'Profitis Ilias',
    'Arsos Lemesou',
    'Nicosia - Walled Old City',
    'Anafotida',
    'Kokkinotrimithia',
    'Avdimou',
    'Frenaros',
    'Platres Kato',
    'Korakou',
    'Agios Thomas',
    'Deftera Kato',
    'Anageia',
    'Episkopeio',
    'Sotira',
    'Timi',
    'Klirou',
    'Paphos - Moutallos',
    'Carolina Park',
    'Amiantos Kato',
    'Apsiou',
    'Koilani',
    'Kapedes',
    'Milia Pafou',
    'Maroni',
    'Tymbou',
    'Kourdali',
    'Ergates',
    'Skarinou',
    'Prodromi',
    'Kathikas',
    'Argaka',
    'Zanakia',
    'Polystypos',
    'Kalavasos',
    'Fasoula Lemesou',
    'Dora',
    'Mosfiloti',
    'Mandria Pafou',
    'Latchi',
    'Akrotiri',
    'Sotira Lemesou',
    'Mathikoloni',
    'Pernera',
    'Kellaki',
    'Agia Varvara Lefkosias',
    'Akrounta',
    'Goudi',
    'Kyperounta',
    'Kornos',
    'Peristerona Lefkosias',
    'Softades',
    'Agios Georgios Kafkalou',
    'Mesa Chorio',
    'Ayia Thekla',
    'Limassol - Agios Antonios',
    'Armenochori',
    'Kakopetria',
    'Mesogi',
    'Akaki',
    'Xylofagou',
    'Agios Theodoros Larnakas'
].sort();

export default function AreaSelector({current = "", changeHandler = () => {}}) {
    return (
        <select id="sel-type" onChange={changeHandler}>
            {areas.map(area =>
                <option value={area} selected={current === area}>{area}</option>
            )}
        </select>
    )
}